### ISSUE TITLE
How i can use it??

### ISSUE THREAD

**Issue by jfernal** [RavishaHesh/PDFJsAnnotations#1]
Hello, can you help me to install it?, i think that is good tool.

**Comment by RavishaHesh** [comment]
You can find the instructions from [https://github.com/RavishaHesh/PDFJsAnnotations/blob/master/index.html](https://github.com/RavishaHesh/PDFJsAnnotations/blob/master/index.html) and [https://github.com/RavishaHesh/PDFJsAnnotations/blob/master/script.js](https://github.com/RavishaHesh/PDFJsAnnotations/blob/master/script.js) if you need further assistance feel free to contact me

**Comment by RavishaHesh** [comment]
It's not possible on the current version. But you can add a text with a color

**Comment by vavicheth** [comment]
Hi sir!
It doesn't work for me.
