### ISSUE TITLE
Touchscreen drawing

### ISSUE THREAD

**Issue by yannicklebras** [RavishaHesh/PDFJsAnnotations#16]
Hi, thank you for this job. 

For me it works great when using the trackpad of my laptop (chromebook Lenovo 500e). But using the touchscreen, free drawing and others don't work. When I draw a line with the touchscreen (finger or stylus) an object seems to be created since i can see it in the Annotation Data but it's "empty" (see above). When I switch to mobile emulation it doesn't work at all. If I reload the page (always in mobile emulation) it works. If I switch back to desktop, it works (!!!) and if I reload the page, always in desktop mode, it fails. 

I tried the free drawing tool in the fabricjs official page and I can draw with the touchscreen and stylus. 

Any Idea how to solve this ? 

thx

Yannick
`{
                "type": "path",
                "originX": "left",
                "originY": "top",
                "left": -0.5,
                "top": -0.5,
                "width": 0,
                "height": 0,
                "fill": null,
                "stroke": "rgb(0, 0, 0)",
                "strokeWidth": 1,
                "strokeDashArray": null,
                "strokeLineCap": "round",
                "strokeLineJoin": "round",
                "strokeMiterLimit": 10,
                "scaleX": 1,
                "scaleY": 1,
                "angle": 0,
                "flipX": false,
                "flipY": false,
                "opacity": 1,
                "shadow": null,
                "visible": true,
                "clipTo": null,
                "backgroundColor": "",
                "fillRule": "nonzero",
                "globalCompositeOperation": "source-over",
                "transformMatrix": null,
                "skewX": 0,
                "skewY": 0,
                "pathOffset": {
                    "x": 0,
                    "y": 0
                },
                "path": [
                    [
                        "M"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "Q"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ],
                    [
                        "L"
                    ],
                    [
                        "a"
                    ],
                    [
                        "a"
                    ]
                ]
            }`

**Comment by hichamhargal** [comment]
that's because of the "isTouchSupported" fabricjs's function. in the version 1.7.22 of Fabric.js used here it's like this : 
`
fabric.isTouchSupported = 'ontouchstart' in fabric.window;
`
which returns false for any browser installed on the laptop even if it's with a touchscreen (Toshiba Protege in my case).

in the latest stable version for example, the 3.6.3, this function is modified to be like this : 
```
fabric.isTouchSupported = 'ontouchstart' in fabric.window || 'ontouchstart' in fabric.document ||
  (fabric.window && fabric.window.navigator && fabric.window.navigator.maxTouchPoints > 0);
```
which returns true in our case.

so, you have just to change the call of the fabric.min.js in your index.html : 

`<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.6.3/fabric.min.js"></script>`

hope that helps.

**Comment by yannicklebras** [comment]
Yes it helps, problem solved.
Thank you !
