### ISSUE TITLE
Load document url dynamically

### ISSUE THREAD

**Issue by abhimanusharma** [RavishaHesh/PDFJsAnnotations#20]
Hi,

I am trying to implement this package with Vuejs, I am successfully integrated it and all features are working as expected. Now only thing I'm struggling with is when, I try to load pdf document dynamically, it show blank space, because initially document load on mounted, 

```
this.pdf = 
	new PDFAnnotate('pdf-container', this.url, {
				onPageUpdated: (page, oldData, newData) => {
					console.table(page, oldData, newData);
				},
				ready: function() {
					this.loadFromJSON(this.docAnnotation);
				}.bind(this)
			});
```

when I try to change the value of this.url dynamically, pdf document won't update. What could be the workaround?

**Comment by RavishaHesh** [comment]
It's not possible to load a different PDF by just changing the URL. To load a different PDF you have to re-initialize the plugin because there's a worker process behind that

**Comment by abhimanusharma** [comment]
Yeah, I did the same thing on the go. Called a method that initialize the plugin every time user select a new document to work with.
Thanks.

**Comment by gruelas16** [comment]
@abhimanusharma  im having the same error, could you share how you did it? or @RavishaHesh  can you post an example of how re-initialize the plugin?

**Comment by abhimanusharma** [comment]
@gruelas16 Here is how I am updating the document url dynamically.

```
updateDocumentUrl(url, annotation, options = {}) {
    this.pdf = 
        new PDFAnnotate('pdf-container', url, {
            onPageUpdated: (page, oldData, newData) => {
                console.table(page, oldData, newData);
            },
            ready: function() {
                if(annotation) {
                    this.loadFromJSON(annotation);
                }
            }.bind(this),
            scale: options.scale?options.scale:1.8,
            pageImageCompression: options.pageImageCompression?options.pageImageCompression:"MEDIUM",
            movable: typeof options.movable!='undefined'?options.movable:true
        }
    );
},

```

then call this function whenever I need to change the url.

```
updateDocumentUrl(url, annotation);
```
