### ISSUE TITLE
How to add date field or textbox field on pdf

### ISSUE THREAD

**Issue by abhimanusharma** [RavishaHesh/PDFJsAnnotations#23]
Hi,

Can we enhance this package so that we can drag/drop a text field or a date field on the pdf document?

Similar functionality exists on a platform called dotloop.

**Comment by RavishaHesh** [comment]
Sorry. This doesn't support for that kind of features since this is an Annotations library.

**Comment by abhimanusharma** [comment]
I implemented this in my project using this package, if anyone is trying something similar then let me know.

**Comment by janlord01** [comment]
> I implemented this in my project using this package, if anyone is trying something similar then let me know.

please share it here. Thanks :)
