### ISSUE TITLE
Background is removed if image is added on canvas object (fabricObj.add(img))

### ISSUE THREAD

**Issue by abhimanusharma** [RavishaHesh/PDFJsAnnotations#24]
@RavishaHesh 

Whenever  try to add image (even static one), the pdf background removed and image will be added on a white background on that canvas.

At first I thought it was an issue in fabric js, that we can not add an Image over a canvas having background image or it will remove the background, but now I have an jsfiddle https://jsfiddle.net/abhimanusharma/2hektx49/24/ where a image is added over an background image. I also tried to create a jsfiddle for PDFJsAnnotations project but it was impossible for me. 
Here is my failed attempt https://jsfiddle.net/abhimanusharma/5b4o0zqj/ 
My Stackoverflow question: https://stackoverflow.com/questions/65074701/add-multiple-images-on-lower-canvas-using-fabric-js

Can you please check why this is happening in your plugin?
Here is how I tried to add the image and external element over the pdf canvas.
See line 123, 238 and 314 to see how I tried to add the Image.
https://github.com/abhimanusharma/PDFJsAnnotations/blob/master/pdfannotate.js

**Update:** Here is the working codesendbox: https://codesandbox.io/s/hardcore-shape-gt8do

Background is removing for some canvas when add image by clicking on image icon than on canvas.

**Comment by abhimanusharma** [comment]
@RavishaHesh Please look into this issue. Thanks

**Comment by RavishaHesh** [comment]
@abhimanusharma I have added support for this option in the latest version. Please check

**Comment by abhimanusharma** [comment]
@RavishaHesh This doesn't solve my purpose as I want to add Image from url. I am using vue-signature-pad to add an image on the canvas. Please add a support to add an image from url as well. Adding image from url is removing background.

**Comment by RavishaHesh** [comment]
@abhimanusharma in that case you have to do little bit of a modification by yourself. add a URL parameter to `addImageToCanvas ` and set `image.src` in 184 to that parameter

**Comment by abhimanusharma** [comment]
This is adding image on top:0 left:0 position but I need to add image on specific coordinate on mouseclick event. As shown in the codesandbox with option selectable:false, so that can not change the position of the image.

**Comment by abhimanusharma** [comment]
@RavishaHesh  The problem still persist if I add image on click on canvas.

**Comment by abhimanusharma** [comment]
@RavishaHesh Can this feature be enhanced to make it add image on the clicked position?

**Comment by abhimanusharma** [comment]
> @abhimanusharma in that case you have to do little bit of a modification by yourself. add a URL parameter to `addImageToCanvas ` and set `image.src` in 184 to that parameter

@RavishaHesh I tried to modify the addImageToCanvas function to add image dynamically but it is not working tried many methods as suggested by you.

```
PDFAnnotate.prototype.addImageToCanvas = function (img) {
	var inst = this;
	var fabricObj = inst.fabricObjects[inst.active_canvas];

	if (fabricObj) {
		var inputElement = document.createElement("input");
		inputElement.type = 'file'
		inputElement.accept = ".jpg,.jpeg,.png,.PNG,.JPG,.JPEG";

		if((typeof img === 'undefined')) {
			inputElement.onchange = function() {
				var reader = new FileReader();
				reader.addEventListener("load", function () {
					inputElement.remove()
					var image = new Image();
					
						image.onload = function () {
							fabricObj.add(new fabric.Image(image))
						}
						image.src = this.result;
					
				}, false);
				reader.readAsDataURL(inputElement.files[0]);
			}
			document.getElementsByTagName('body')[0].appendChild(inputElement)
			inputElement.click();
		} else {
			var image = new Image();
			image.src = img.src;
			
			fabricObj.add(new fabric.Image(image, {
				left: img.left,
				top: img.top,
				angle: 0,
				opacity: 1
			}));

			fabric.Image.fromURL(img.src, function(oImg) {
				oImg.scale(0.75).set({
					left: img.left,
					top: img.top,
					angle: 0,
					opacity: 1
				});
				fabricObj.add(oImg);
			  });
		}
	} 
}
```
