### ISSUE TITLE
Question ? Usage of latest version of fabric and pdf 

### ISSUE THREAD

**Issue by comcorba** [RavishaHesh/PDFJsAnnotations#25]
Hello, 
I have two points.  I modified the codes to support latest libraries of pdfjs and fabric  

Fabric gives error   : Error loading data:, fabric.min.js:1:871 and it doesn't show pdf. Do you have plan to use latest versions of js libraries? 

Second point is that : the pdf on the screen is not sharp and  blur. How does  resolution of pdf can be improved.  

var pdfjsLib = window['pdfjs-dist/build/pdf'];
// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.worker.min.js';

https://cdnjs.cloudflare.com/ajax/libs/fabric.js/4.3.0/fabric.min.js 
https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js

Thanks 
Turgut

**Comment by RavishaHesh** [comment]
@comcorba I have updated PDFJs, FabricJS and jsPDF plugins to the latest versions. Not sure about the blurry issue. Can you attach a screenshot?

**Comment by comcorba** [comment]
Hello RavishaHesh, 

Thanks for prompt return and update of source code. it works with the pdf you shared. on the other side,  let me list down some issues  i came across. Maybe these are not directly related to your library  but your inputs will be appreciated.  

**1-Sample pdfs are not being displayed and error comes.** 

"Object { message: "Missing PDF \"http://localhost:9090/helloworld/html_test/sample.pdf\".", name: "MissingPDFException", stack: "BaseExceptionClosure@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:21721\n@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:21792\n__w_pdfjs_require__@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:438\n@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:6602\n__w_pdfjs_require__@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:438\n@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:4864\n__w_pdfjs_require__@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:438\n@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:1524\n@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:1569\nwebpackUniversalModuleDefinition@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:290\n@https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.6.347/pdf.min.js:22:294\n" }
pdfannotate.js:54:14
    PDFAnnotate http://localhost:9090/helloworld/html_test/pdfannotate.js:54"

[sample.pdf](https://github.com/RavishaHesh/PDFJsAnnotations/files/5744264/sample.pdf)

Please see the attached pdf. 

**2-if i try to save the document , it doesnt show all pdf and some part are cropped.** 

3-Blur wise, there is difference on the display . Please check the attached images. 
pdf_on_pdfjs.jpg
pdf_on_acrobat_reader.jpg

![pdf_on_acrobat_reader](https://user-images.githubusercontent.com/19655941/103167665-9171d880-4846-11eb-8a2d-01c8294d89af.jpg)

![pdf_on_pdfjs](https://user-images.githubusercontent.com/19655941/103167664-8f0f7e80-4846-11eb-9010-3bd14df4b156.jpg)

3- Saving button only brings first page . is there any reason why The second and third pages and fourth, fifth  page don't comes.

 
Thanks 
Turgut

**Comment by comcorba** [comment]
let me add sample pdf one more time 
[sample.pdf](https://github.com/RavishaHesh/PDFJsAnnotations/files/5744349/sample.pdf)

**Comment by RavishaHesh** [comment]
"Missing PDF "http://localhost:9090/helloworld/html_test/sample.pdf\" means that PDFJS can't find the pdf in given URL. paste this link to the address bar of the browser and check if it works

**Comment by comcorba** [comment]
somehow browsers keeps caching the page caused me mistake. now i can see sample pdf coming. i see that there is still problem on the saving part.

**Comment by RavishaHesh** [comment]
@comcorba can you check with the latest update.

**Comment by comcorba** [comment]
Thanks. the last update solved the problem. I think the big problem is here that generated pdf/saved one's quality is really not very good. i see  that rendered output to browser from pdfjs's doesn't come  that great. i attached the both.  i think it is better to use an other library on the backed and send fabric  objects to backend system to generate an other pdf by using original pdf and  received images
 you can see the difference the attached images.     

[generated_one.pdf](https://github.com/RavishaHesh/PDFJsAnnotations/files/5744847/generated_one.pdf)
[orginal_one.pdf](https://github.com/RavishaHesh/PDFJsAnnotations/files/5744848/orginal_one.pdf)

**Comment by RavishaHesh** [comment]
The main reason for that quality issue is because output PDF doesn't have the text layer. It's just a set of images. I'm trying to fix this in the next version with text layer but since PDFJS doesn't have a proper documentation it's bit time consuming. For now try setting `scale` to `1` and `pageImageCompression` to `NONE` which will render un-compressed PNG images. But the file size will be much higher than the original one.
I'm closing this issue for now. Feel free to open again if you have any further questions.
