### ISSUE TITLE
Save generated file to desired location instead of downloading

### ISSUE THREAD

**Issue by zeecorleone** [RavishaHesh/PDFJsAnnotations#28]
currently when we call `savePdf`, it calls `doc.save(fileName)`. This eventually writes the files to the response. _i.e, the file is downloaded_. Which is cool. But what if I want to save the generated/edited file to some xyz location on server? I'm getting hard time in understanding if I could get hold of some stream that I can write somewhere, or to pass it to an API, etc.

there is a method `doc.output` that returns some complex string, which seems to be PDF metadata or something. Is this something that I'll have to use? if so, how?

**Summary:**
How can I get stream/file that I can use to create file on server or to send it to an API that will eventually create file out of it.
Currently it is downloading, and I want to override this behavior.

Any directions/guidelines would be appreciated.

**Comment by zeecorleone** [comment]
@RavishaHesh

**Comment by RavishaHesh** [comment]
You should be able to get an idea from this https://github.com/RavishaHesh/PDFJsAnnotations/issues/27#issuecomment-757938421
Please do let me know i you need further assistance

**Comment by zeecorleone** [comment]
@RavishaHesh , great, that will help ! .. One more similar question, is it anyway possible to write the changes to the same document where it is loading from?

**Comment by RavishaHesh** [comment]
No it's not possible and also not recommended. Because output of this lib is a PDF file with set of images as pages which will remove the text layer of the PDF

**Comment by zeecorleone** [comment]
Thanks.
