### ISSUE TITLE
add image on the clicked position

### ISSUE THREAD

**Issue by abhimanusharma** [RavishaHesh/PDFJsAnnotations#29]
I need to store the image position also in the database, as per new version image adding feature is there but it will be added on 0,0 position. I don't want user to change its position so I want the image to be added in  a fixed position and save that position in the db to load it later.

**Comment by RavishaHesh** [comment]
You can customize [line 185](https://github.com/RavishaHesh/PDFJsAnnotations/blob/cb4131d865b981a8599138b7bd89bbf580ea845d/pdfannotate.js#L185) according to this http://fabricjs.com/fabric-intro-part-1#images

**Comment by abhimanusharma** [comment]
Closing this issue, as this might be fixed automatically after updating the package and its dependencies.
