### ISSUE TITLE
Is it possible to Add Draw Rectangle with border alone feature to annotate? 

### ISSUE THREAD

**Issue by jinuem** [RavishaHesh/PDFJsAnnotations#3]
Is it possible to Add Draw Rectangle with border alone feature to annotate? 

So User can click Rectangle icon and 
select the text or image to marked inside rectangle to annotate.

**Comment by RavishaHesh** [comment]
No it's not possible, because the final output is a PDF file with images of the pages with annotations(text or drawings)

**Comment by jinuem** [comment]
@RavishaHesh  thanks for replying. 
What i meant was, like text or drawing. can we draw a rectangle to annotation and get the JSON object of it.?

**Comment by RavishaHesh** [comment]
Sorry, I misunderstood your question. Rectangle tool does not support in current version. But I'm planning to rewrite the library soon(probably within this weekend  🤞) with few features and I'm planning to add rectangle tool too.

**Comment by jinuem** [comment]
@RavishaHesh Wow. Thanks. I am waiting. :)

**Comment by jinuem** [comment]
@RavishaHesh  any update on the Rectangle?

**Comment by RavishaHesh** [comment]
Sorry @jinuem it seems new version needs more time than I planned, I'm trying to add the text layer and it's littlebit tricky, but I'll try to add rectangle feature to the current version within next two days.

**Comment by jinuem** [comment]
@RavishaHesh  Thanks man. :) Awaiting for that ..

**Comment by RavishaHesh** [comment]
@jinuem Added rectangle tool to the master branch
