### ISSUE TITLE
How to render fillable PDF 

### ISSUE THREAD

**Issue by mohdafzalansari** [RavishaHesh/PDFJsAnnotations#37]
I have used this repository and working that I was looking for.
But I am facing issues when trying to render fillable PDF it is not rendered correctly means controls(textbox, radio button, etc) are not able to fillable.

Can help me with how can I achieve this feature.

**Comment by RavishaHesh** [comment]
Unfortunately this library does not support some PDF features like form fields yet
 
![Capture](https://user-images.githubusercontent.com/6573956/124389609-99cf3280-dd05-11eb-85d1-59e36eb11967.PNG)

**Comment by mohdafzalansari** [comment]
Thanks for your reply
