### ISSUE TITLE
Want to highlight text 

### ISSUE THREAD

**Issue by webiknows** [RavishaHesh/PDFJsAnnotations#4]
Sir your code is wonderful and thanks,just wanted a feature to highlight text can you help please

**Comment by RavishaHesh** [comment]
I'll try to add as soon as possible, but if it's urgent I have used fabric js for drawings. you can use [Polygon](http://fabricjs.com/docs/fabric.Polygon.html) for highlighting with low opacity color.

**Comment by RavishaHesh** [comment]
@webiknows I Just added rectangle tool to the master branch. you can use it for highlighting with low opacity fill color(i.e. `rgba(255,0,0,0.3)`)
