### ISSUE TITLE
Hello and thank you

### ISSUE THREAD

**Issue by Splashdown** [RavishaHesh/PDFJsAnnotations#5]
Hi Sir,

This is exactly what i need in my current project. !! Awesome.
I got a vue js and laravel stack, this is a great inspiration source to help to do what i need. 

Thank you for this, i will take a look in the future if i can help you :)

**Comment by RavishaHesh** [comment]
@Splashdown  You are welcome and thank you very much.
I haven't had time to work on this for a while. But I planning to add some features specially the text layer, so if you want to contribute to this project, welcome aboard!
