### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by khaledmndev** [RavishaHesh/PDFJsAnnotations#56]
i'm having an issue while retrieving json data from the storage after parsing it

here's my code:

```
 var data1 = JSON.parse(localStorage.getItem('CanvaData'));
 pdf.loadFromJSON(data1)
```

Error:
```
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at i.loadFromJSON (fabric.min.js:1:131008)
at i. (pdfannotate.js:286:14)
at Function.each (jquery.min.js:2:2976)
at PDFAnnotate.loadFromJSON (pdfannotate.js:284:4)
at Object.ready (script.js:15:13)
at HTMLCanvasElement. (pdfannotate.js:87:13)
at Function.each (jquery.min.js:2:2976)
at S.fn.init.each (jquery.min.js:2:1454)
at PDFAnnotate.initFabric (pdfannotate.js:60:15)
```

and it's working perfectly when i manually paste the json data into `pdf.loadFromJSON([here])`

**Comment by RavishaHesh** [comment]
I don't think `JSON.parse` is necessary if you save it in the local storage. can you try without it?

**Comment by khaledmndev** [comment]
> I don't think `JSON.parse` is necessary if you save it in the local storage. can you try without it?

this one worked perfectly, thanks, just a question, is there anyway to integrate this with [dflipjs](https://dearflip.com/realistic-3d-flipbook-wordpress-plugin/) library? it also uses PDF.js

**Comment by RavishaHesh** [comment]
it might be possible, but that's not going to be easy. you have hack into the plugin's code

**Comment by khaledmndev** [comment]
@RavishaHesh alright thanks for helping me, but just one annoying question, is there a way to save the canvas without the psd images to json? To reduce the of the json output, this way i can load the psd file alone and import the canvas from the json..
