### ISSUE TITLE
Can i free draw rectangle?

### ISSUE THREAD

**Issue by Ketan-Infyom** [RavishaHesh/PDFJsAnnotations#7]
Right now, rectangle can be drawn with static width and height. is it possible to freely draw rectangle with any height and width in current version?

**Comment by Splashdown** [comment]
Hey @Ketan-Infyom Im not a contributors but its not possible to draw a free rectangle with this version.
However you can click on the rectangle tools, click on the generated rectangle (on the top left), and resize him :)

Hope this help !

**Comment by RavishaHesh** [comment]
Thanks @Splashdown, @Ketan-Infyom As he said you can resize using edges to any size

**Comment by Ketan-Infyom** [comment]
Thanks @Splashdown. Spe. thanks to @RavishaHesh for creating such a tool. 
@RavishaHesh do you have any plan to add such a feature(s)?

**Comment by RavishaHesh** [comment]
Not on current "to-do" list. My entire focus is to implement text layer for now because it's the biggest down-side of this package. I'm using [FabricJS](http://fabricjs.com/) for drawing. If you can find a way to free-draw a rectangle using that, I can it to this.
