### ISSUE TITLE
Does I get edited annotations object while re-edit same pdf again?

### ISSUE THREAD

**Issue by iamharshad** [RavishaHesh/PDFJsAnnotations#8]
Hey, I want to know that, Is it possible to get edited annotation while editing the same pdf again?
And how can I go for that?

**Comment by RavishaHesh** [comment]
Sorry @iamharshad I can't understand your question. Can you describe it with little-bit more details. If you want to change existing shape or text, you should be able to do that by simply clicking on the object

**Comment by iamharshad** [comment]
Let I give you steps.
1. first of all I'm add annotations of shape or text on `test.pdf`
2. Now I'm saving that `test.pdf` and close
3. Now I reopen that `test.pdf` so can I get saved annotations and can I edit those annotations again?

**Comment by RavishaHesh** [comment]
@iamharshad see my answer on [Issue 9](https://github.com/RavishaHesh/PDFJsAnnotations/issues/9)

**Comment by RavishaHesh** [comment]
@iamharshad I'm closing this issue, hope you got the answer
