### ISSUE TITLE
Serialize all canvas data into JSON and re-draw

### ISSUE THREAD

**Issue by Ketan-Infyom** [RavishaHesh/PDFJsAnnotations#9]
@RavishaHesh I want to Serialize all canvas data into JSON and re-draw, how can I achieve it?

Steps (for elaboration):
1) add annotations to pdf file
2) get all `annotations`
3) now save `pdf` file with `annotations` and close the project
4) now open that `pdf`, I want back those `annotations` and also need to change it.

Is this possible in this package? if yes how can I achieve it?

**Comment by RavishaHesh** [comment]
Okay, I just added `loadFromJSON (serializedJsonData)` method. But haven't had enough time to test it properly, let me know if you run into any issues. Thanks

**Comment by Ketan-Infyom** [comment]
@RavishaHesh Thanks,  It's working fine.

**Comment by ArrNNG** [comment]
Hi,I having the same issues here.
How to use `loadFromJSON` ?
I put it on ` $(function () {}`,the `inst.fabricObjects`  's lenth is 0. 
Did I use it wrong?

**Comment by RavishaHesh** [comment]
> Hi,I having the same issues here.
> How to use `loadFromJSON` ?
> I put it on ` $(function () {}`,the `inst.fabricObjects` 's lenth is 0.
> Did I use it wrong?

As readme says you have to initialize plugin first

**Comment by jesesqui** [comment]
> 

can I see your code/example?

**Comment by adeelahmed233** [comment]
> Hi,I having the same issues here. How to use `loadFromJSON` ? I put it on ` $(function () {}`,the `inst.fabricObjects` 's lenth is 0. Did I use it wrong?

How can I add an image on top of pdf whenever pdf opens? 
It relates to pdf.loadFromJSON(serializedJSON) I think. 
Can you please provide sample code?
